#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 29, 2019 07:16:43 PM CEST  platform: Windows NT

import sys
from sql import *

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Schritt2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Schritt2_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Schritt2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, fname,lname,top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#050154'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1440x837+487+188")
        top.title("Schritt 2")
        top.configure(background="#050154")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.118, rely=0.06,height=20, relwidth=0.267)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=384)

        self.Entry1_1 = tk.Entry(top)
        self.Entry1_1.place(relx=0.118, rely=0.119,height=20, relwidth=0.267)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1.configure(selectforeground="black")
        self.Entry1_1.configure(width=384)

        self.Entry1_2 = tk.Entry(top)
        self.Entry1_2.place(relx=0.118, rely=0.179,height=20, relwidth=0.267)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font="TkFixedFont")
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="#c4c4c4")
        self.Entry1_2.configure(selectforeground="black")
        self.Entry1_2.configure(width=384)

        self.Entry1_3 = tk.Entry(top)
        self.Entry1_3.place(relx=0.118, rely=0.239,height=90, relwidth=0.267)
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(disabledforeground="#a3a3a3")
        self.Entry1_3.configure(font="TkFixedFont")
        self.Entry1_3.configure(foreground="#000000")
        self.Entry1_3.configure(highlightbackground="#d9d9d9")
        self.Entry1_3.configure(highlightcolor="black")
        self.Entry1_3.configure(insertbackground="black")
        self.Entry1_3.configure(selectbackground="#c4c4c4")
        self.Entry1_3.configure(selectforeground="black")
        self.Entry1_3.configure(width=384)

        self.Entry1_4 = tk.Entry(top)
        self.Entry1_4.place(relx=0.118, rely=0.358,height=20, relwidth=0.267)
        self.Entry1_4.configure(background="white")
        self.Entry1_4.configure(disabledforeground="#a3a3a3")
        self.Entry1_4.configure(font="TkFixedFont")
        self.Entry1_4.configure(foreground="#000000")
        self.Entry1_4.configure(highlightbackground="#d9d9d9")
        self.Entry1_4.configure(highlightcolor="black")
        self.Entry1_4.configure(insertbackground="black")
        self.Entry1_4.configure(selectbackground="#c4c4c4")
        self.Entry1_4.configure(selectforeground="black")
        self.Entry1_4.configure(width=384)

        self.Entry1_5 = tk.Entry(top)
        self.Entry1_5.place(relx=0.118, rely=0.418,height=20, relwidth=0.267)
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(disabledforeground="#a3a3a3")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(foreground="#000000")
        self.Entry1_5.configure(highlightbackground="#d9d9d9")
        self.Entry1_5.configure(highlightcolor="black")
        self.Entry1_5.configure(insertbackground="black")
        self.Entry1_5.configure(selectbackground="#c4c4c4")
        self.Entry1_5.configure(selectforeground="black")

        self.Entry1_6 = tk.Entry(top)
        self.Entry1_6.place(relx=0.215, rely=0.454,height=70, relwidth=0.169)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="#c4c4c4")
        self.Entry1_6.configure(selectforeground="black")
        self.Entry1_6.configure(width=244)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.0, rely=0.06, height=21, width=154)
        self.Label1.configure(background="#050154")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''RFID Karte Oder Chip''')
        self.Label1.configure(width=154)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.007, rely=0.131, height=21, width=134)
        self.Label2.configure(background="#050154")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Mutter''')
        self.Label2.configure(width=134)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.0, rely=0.191, height=21, width=154)
        self.Label3.configure(background="#050154")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''Vater''')
        self.Label3.configure(width=154)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.028, rely=0.275, height=21, width=94)
        self.Label4.configure(background="#050154")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(text='''Adressen''')
        self.Label4.configure(width=94)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.014, rely=0.358, height=21, width=124)
        self.Label5.configure(background="#050154")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''Tel.Mutter''')
        self.Label5.configure(width=124)

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.0, rely=0.418, height=21, width=154)
        self.Label6.configure(background="#050154")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(text='''Tel.Vater''')
        self.Label6.configure(width=154)

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.0, rely=0.478, height=21, width=304)
        self.Label7.configure(background="#050154")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(text='''Kommentare (bei nichts einfach  ,,Nichts'' hinschreiben)''')
        self.Label7.configure(width=304)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.007, rely=0.012, height=24, width=87)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Zurück''')
        self.Button1.configure(width=87)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.069, rely=0.012, height=24, width=97)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Fertig''')
        self.Button2.configure(width=97)
        self.Button2.configure(command=)

if __name__ == '__main__':
    vp_start_gui()





